name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  pack:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: honeycombio/gha-buildevents@v2
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          status: ${{ job.status }}

      - uses: actions/checkout@v4

      - run: |
          STEP_ID="install dependencies"
          echo "STEP_ID=${STEP_ID}" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: npm ci

      - run: |
          STEP_ID=lint
          echo "STEP_ID=${STEP_ID}" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: npm run lint

      - run: |
          STEP_ID=format-check
          echo "STEP_ID=${STEP_ID}" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: npm run format-check

      - run: |
          STEP_ID=build
          echo "STEP_ID=${STEP_ID}" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: npm run build

      - run: |
          STEP_ID=pack
          echo "STEP_ID=${STEP_ID}" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: npm run pack

      - name: Verify no changes were made
        run: |
          if ! git diff --quiet; then
            echo "Changes detected! Please run 'npm run all' before committing code changes."
            exit 1
          fi
